### ISSUE TITLE
Maximum call stack size exceeded at height:1248134

### ISSUE THREAD

**Issue by siriusyim** [dataswap/messagehub#101]
```
cur sync height: 1248134
[Nest] 82031  - 2024/01/17 11:48:00   ERROR [ExceptionsHandler] Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at BigIntToStringInterceptor.transformBigIntToString (/Users/sirius/works/src/github.com/dataswap/messagehub/src/shared/bigIntToStringInterceptor.ts:62:32)
    at BigIntToStringInterceptor.transformBigIntToString (/Users/sirius/works/src/github.com/dataswap/messagehub/src/shared/bigIntToStringInterceptor.ts:67:26)
    at BigIntToStringInterceptor.transformBigIntToString (/Users/sirius/works/src/github.com/dataswap/messagehub/src/shared/bigIntToStringInterceptor.ts:67:26)
    at BigIntToStringInterceptor.transformBigIntToString (/Users/sirius/works/src/github.com/dataswap/messagehub/src/shared/bigIntToStringInterceptor.ts:67:26)
    at BigIntToStringInterceptor.transformBigIntToString (/Users/sirius/works/src/github.com/dataswap/messagehub/src/shared/bigIntToStringInterceptor.ts:67:26)
    at BigIntToStringInterceptor.transformBigIntToString 
```

**Comment by lovel8** [comment]
The business layer has circumvented this problem,close
