### ISSUE TITLE
messagehub service interruption

### ISSUE THREAD

**Issue by Kennynauh** [dataswap/messagehub#121]
1/19/2024, 6:02:01 AM Warning: error.code=ERR_BAD_RESPONSE, retrying RPC the 1 times
1/19/2024, 6:02:01 AM Warning: error.code=ERR_BAD_RESPONSE, retrying RPC the 2 times
1/19/2024, 6:02:01 AM Warning: error.code=ERR_BAD_RESPONSE, retrying RPC the 3 times
1/19/2024, 6:02:02 AM Error: error.code=ERR_BAD_RESPONSE, already retried RPC 3 times

/home/messagehub/messagehub/src/backgroundTask/provider/backgroundTask.service.ts:45
            throw new Error(`Error in the background task:${error}`)
                  ^
Error: Error in the background task:Error: Error: getChainHeadHeight error:AxiosError: Request failed with status code 503
    at BackgroundTaskService.<anonymous> (/home/messagehub/messagehub/src/backgroundTask/provider/backgroundTask.service.ts:45:19)
    at Generator.throw (<anonymous>)
    at rejected (/home/messagehub/messagehub/dist/src/backgroundTask/provider/backgroundTask.service.js:12:65)

**Comment by Kennynauh** [comment]
Second service stop：

1/19/2024, 4:40:26 PM Warning: error.code=ECONNRESET, retrying RPC the 1 times
1/19/2024, 4:40:26 PM Warning: error.code=ECONNRESET, retrying RPC the 1 times
1/19/2024, 4:40:32 PM Warning: error.code=ECONNRESET, retrying RPC the 1 times
1/19/2024, 4:40:35 PM Warning: error.code=ECONNRESET, retrying RPC the 1 times
1/19/2024, 4:40:37 PM Warning: error.code=ECONNRESET, retrying RPC the 1 times
1/19/2024, 4:40:40 PM Warning: error.code=ECONNRESET, retrying RPC the 2 times
1/19/2024, 4:40:43 PM Warning: error.code=ECONNRESET, retrying RPC the 2 times
1/19/2024, 4:40:46 PM Warning: error.code=ECONNRESET, retrying RPC the 1 times
1/19/2024, 4:40:48 PM Warning: error.code=ECONNRESET, retrying RPC the 3 times

/home/messagehub/messagehub/src/backgroundTask/provider/backgroundTask.service.ts:45
            throw new Error(`Error in the background task:${error}`)
                  ^
Error: Error in the background task:Error: Error: storeSelectedParams error_2:undefined
    at BackgroundTaskService.<anonymous> (/home/messagehub/messagehub/src/backgroundTask/provider/backgroundTask.service.ts:45:19)
    at Generator.throw (<anonymous>)
    at rejected (/home/messagehub/messagehub/dist/src/backgroundTask/provider/backgroundTask.service.js:12:65)

**Comment by Kennynauh** [comment]
/home/messagehub/messagehub/src/backgroundTask/provider/backgroundTask.service.ts:45
            throw new Error(`Error in the background task:${error}`)
                  ^
Error: Error in the background task:Error: Error: storeSelectedParams error_2:Error: the matchings is none
    at BackgroundTaskService.<anonymous> (/home/messagehub/messagehub/src/backgroundTask/provider/backgroundTask.service.ts:45:19)
    at Generator.throw (<anonymous>)
    at rejected (/home/messagehub/messagehub/dist/src/backgroundTask/provider/backgroundTask.service.js:12:65)

**Comment by Kennynauh** [comment]
/home/messagehub/messagehub/src/backgroundTask/provider/backgroundTask.service.ts:45
            throw new Error(`Error in the background task:${error}`)
                  ^
Error: Error in the background task:Error: Error: getChainHeadHeight error:Error: socket hang up
    at BackgroundTaskService.<anonymous> (/home/messagehub/messagehub/src/backgroundTask/provider/backgroundTask.service.ts:45:19)
    at Generator.throw (<anonymous>)
    at rejected (/home/messagehub/messagehub/dist/src/backgroundTask/provider/backgroundTask.service.js:12:65)

**Comment by Kennynauh** [comment]
1/26/2024, 7:44:48 AM Warning: error.code=EAI_AGAIN, retrying RPC the 1 times
1/30/2024, 7:48:23 PM Warning: error.code=ECONNRESET, retrying RPC the 1 times
1/30/2024, 7:50:24 PM Warning: error.code=ERR_BAD_RESPONSE, retrying RPC the 1 times
1/30/2024, 7:50:24 PM Warning: error.code=ERR_BAD_RESPONSE, retrying RPC the 2 times
1/30/2024, 7:50:24 PM Warning: error.code=ERR_BAD_RESPONSE, retrying RPC the 3 times
1/30/2024, 7:50:24 PM Error: error.code=ERR_BAD_RESPONSE, already retried RPC 3 times

/home/messagehub/messagehub/src/backgroundTask/provider/backgroundTask.service.ts:45
            throw new Error(`Error in the background task:${error}`)
                  ^
Error: Error in the background task:Error: Error: getChainHeadHeight error:AxiosError: Request failed with status code 503
    at BackgroundTaskService.<anonymous> (/home/messagehub/messagehub/src/backgroundTask/provider/backgroundTask.service.ts:45:19)
    at Generator.throw (<anonymous>)
    at rejected (/home/messagehub/messagehub/dist/src/backgroundTask/provider/backgroundTask.service.js:12:65)
